---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2




provisioner:
  name: chef_solo

platforms:
  - name: chef/debian-7.7

suites:
  - name: default
    run_list:
      - recipe[debian-backports]
      - recipe[debian-backports::package]
    attributes: {
      backports: {
        install: [ 'duplicity' ]
        }
      }

